services:
    laravel.test:
        container_name: 'Staging'
        build:
            context: ../
            dockerfile: staging/Dockerfile
        environment:
            NODE_VERSION: 22
            PHP_VERSION: 8.4
        volumes:
            - 'storage_volume:/var/www/html/storage'
