services:
    laravel.test:
        container_name: 'Staging'
        build:
            context: .
            dockerfile: staging/Dockerfile
        expose:
            - '80'
        volumes:
            - 'storage_volume:/var/www/html/storage'
