# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - master

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
  phpVersion: 7.3

steps:
  - script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    displayName: 'Use PHP version $(phpVersion)'

  - script: composer install --no-interaction --prefer-dist
    displayName: 'Install server side dependencies'

  - script: |
      curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      sudo apt-get install -y build-essential nodejs
    displayName: 'Install NodeJS'

  - script: npm install
    displayName: 'Install client-side dependencies'

  - script: npm run prod
    displayName: 'Compile client-side dependencies'

  - script: rm -rf storage
    displayName: 'Remove storage directory'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
      replaceExistingArchive: true
    displayName: 'Archive build'

  - script: 'openssl md5 $(Build.ArtifactStagingDirectory)/build.zip | cut -d" " -f2 > $(Build.ArtifactStagingDirectory)/checksum.txt'
    displayName: 'Calculating checksum'

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: '$(Hosting server)'
      username: '$(Hosting user)'
      password: '$(Hosting password)'
      rootDirectory: '$(Build.ArtifactStagingDirectory)'
      filePatterns: 'checksum.txt'
      remoteDirectory: '/'
      clean: false
      cleanContents: true
      preservePaths: false
      trustSSL: false
    displayName: 'Upload checksum to server'

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: '$(Hosting server)'
      username: '$(Hosting user)'
      password: '$(Hosting password)'
      rootDirectory: '$(Build.ArtifactStagingDirectory)'
      filePatterns: 'build.zip'
      remoteDirectory: '/'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false
    displayName: 'Upload build artifacts to server'
