name: Lint and build front end JS
on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: ðŸ” Read Env
              run: grep -E 'NODE_VERSION' .env.prod >> $GITHUB_ENV

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: npm

            - run: npm ci --ignore-scripts

            - name: Run eslint
              run: |
                  npx eslint resources/ --fix

            - name: Cache Prettier
              uses: actions/cache@v4
              with:
                path: .tmp/prettier
                key: ${{ runner.os }}-prettier-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
                restore-keys: |
                  ${{ runner.os }}-prettier-${{ hashFiles('**/composer.lock') }}-
                  ${{ runner.os }}-prettier-

            - name: Run Prettier
              run: |
                mkdir -p .tmp/prettier
                npx prettier resources/ --write --cache --cache-location=.tmp/prettier --cache-strategy metadata

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Automatic linting (Prettier and eslint)

            - name: ðŸ“¥ Download WayFinder Artifact
              uses: actions/download-artifact@v4
              with:
                  name: wayfinder-actions
                  path: resources/js/

            - name: ðŸ”¨ build front-end
              run: |
                  npm run build

            - name: ðŸ“¤ Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: compiled-assets
                  path: public/build/
                  if-no-files-found: error
                  retention-days: 1
